### ISSUE TITLE
O site HandcodeJr.github.io não está sendo exibido.

### ISSUE THREAD

**Issue by alcemirsantos** [HandcodeJr/HandcodeJr.github.io#1]
Ao usar o endereço URL para acessar a página, somente o `Readme.md` é exibido. Não sei se é de propósito, por isso cadastrei o issue.

**Comment by gustavorw** [comment]
No caso vamos hospedar em outra plataforma

**Comment by alcemirsantos** [comment]
Neste caso, o repositório deveria estar privado, não?

**Comment by gustavorw** [comment]
Erros chefe, na próxima vamos seguir suas recomendações .
